# McCulloch-Pitts
ayuda_mp:
	@echo "----------------------------------------------------"
	@echo "HELP Neural Network - McCulloch-Pitts"
	@echo "	-- No arguments available"
	@echo "----------------------------------------------------"

compila_mp:
	@echo "----------------------------------------------------"
	@echo "Compiling Neural Network - McCulloch-Pitts"
	@echo "--Nothing to do"
	@echo "----------------------------------------------------"

ejecuta_mp:
	@echo "----------------------------------------------------"
	@echo "Executing Neural Network - McCulloch-Pitts"
	@echo "----------------------------------------------------"
	python3 mcculloch.py 

# Compile all
compilar:
	@echo "----------------------------------------------------"
	@echo "Compiling Neural Network - Perceptron"
	@echo "--Nothing to do"
	@echo "Compiling Neural Network - Adaline"
	@echo "--Nothing to do"
	@echo "----------------------------------------------------"

# Perceptron
ayuda_per:
	@echo "----------------------------------------------------"
	@echo "HELP Neural Network - Perceptron"
	@echo "	--alpha		<value>		Value between 0.0 and 1.0"
	@echo "	--umbral	<value> 	Value between 0.0 and 1.0"
	@echo "	--prop 		<value>		Value between 0.0 and 1.0"
	@echo "	--tolerance	<value> 	Value between 0.0 and 1.0"
	@echo "	--patience 	<value>		Integer value max iterations"
	@echo "	--train <file> 	Training file name"
	@echo "	--test <file> 	Testing file name"
	@echo "----------------------------------------------------"

ejecuta_per:
	@echo "----------------------------------------------------"
	@echo "Executing Neural Network - Perceptron"
	@echo "----------------------------------------------------"
	python3 perceptron.py 

# Adaline
ayuda_ada:
	@echo "----------------------------------------------------"
	@echo "HELP Neural Network - Adaline"
	@echo "----------------------------------------------------"

ejecuta_ada:
	@echo "----------------------------------------------------"
	@echo "Executing Neural Network - Adaline"
	@echo "----------------------------------------------------"
	python3 adaline.py 