all:

ayuda_mp:
	@echo "----------------------------------------------------"
	@echo "HELP Neural Network - McCulloch-Pitts"
	@echo "----------------------------------------------------"

compila_mp:
	@echo "----------------------------------------------------"
	@echo "Compiling Neural Network - McCulloch-Pitts"
	@echo "----------------------------------------------------"

ejecuta_mp:
	@echo "----------------------------------------------------"
	@echo "Executing Neural Network - McCulloch-Pitts"
	@echo "----------------------------------------------------"
	python3 simulation.py 
	